[project]
name = "mcp-fetch-server"
version = "0.1.0"
description = "MCP server for fetching web content"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.27.0",
    "html2text>=2024.2.26",
    "pydantic>=2.0.0",
]

[tool.uv]
dev-dependencies = []