[project]
name = "mcp-terminal-server"
version = "1.0.0"
description = "MCP Terminal Server for command execution"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.8.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"